import "./globals.css";

import { ClerkProvider } from '@clerk/nextjs'
import { dark, neobrutalism } from '@clerk/themes'

export const metadata = {
  title: "Tattva Watch | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
      variables: {
        colorPrimary: '#00ff66'
      }
    }}>
      <html lang="en">
        <body className={`antialiased dark`}>
            {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
